import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { useEffect, useState } from 'react'

export default function Home() {
  const [ items, setItems ] = useState(['⚡️','🎨','🔥','🐛','🚑️','✨'])
  
  async function loadDrag(){
    const { Draggable, Sortable, Plugins } = await import(/* webpackChunkName: "user-defined" */'@shopify/draggable')

    // const draggable = new Draggable(document.querySelectorAll('ul'), {
    //   draggable: 'li',
    //   exclude: {
    //     plugins: [Draggable.Plugins.Focusable],
    //     sensors: [Draggable.Sensors.TouchSensor],
    //   }
    // });

    

    const containers = document.querySelectorAll('ul');

    if (containers.length === 0) {
      return false;
    }

    const sortable = new Sortable(containers, {
      draggable: 'li',
      mirror: {
        constrainDimensions: true,
      },
      plugins: [Plugins.SortAnimation],
      swapAnimation: {
        duration: 200,
        easingFunction: 'ease-in-out',
      }     
    });

    return sortable;
  }

  useEffect(()=>{   
    if (typeof(window)!=="undefined") window.addEventListener('load', loadDrag);
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Drag and Drop - playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <ul>
          {
            items.map((i)=>(
              <li key={i}>{i}</li>
            ))
          }
        </ul>
      </main>
    </div>
  )
}
